FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libegl1 \
    libgles2 \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-liveness.txt .

RUN pip install --no-cache-dir -r requirements-liveness.txt

COPY . .

CMD ["sh", "-c", "uvicorn liveness_api:app --host 0.0.0.0 --port ${PORT:-10000}"]